version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: narravo
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: narravo
    ports: ["5432:5432"]
    volumes: [ "pg-data:/var/lib/postgresql/data" ]
volumes:
  pg-data:
