# Performance Monitoring CI
name: Performance

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  performance-check:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: narravo_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup database
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/narravo_test
      run: |
        npm run drizzle:push
        npm run seed:config
    
    - name: Run TypeScript check
      run: npm run typecheck
    
    - name: Run tests
      run: npm test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/narravo_test
    
    - name: Build application
      run: npm run build
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/narravo_test
        ANALYZE: true
    
    - name: Bundle size check
      run: |
        # Check if any JS bundle exceeds our budget (90KB for post pages)
        find .next/static/chunks -name "*.js" -size +90k -ls || true
        echo "Bundle size check completed"
    
    - name: Start application for testing
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3000/healthz || (echo "Health check failed" && exit 1)
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/narravo_test
      timeout-minutes: 2
    
    - name: Run Lighthouse CI
      run: |
        # Install Lighthouse CI if not cached
        npx lhci autorun --config=lighthouserc.json --collect.url="http://localhost:3000" || echo "Lighthouse CI skipped - service may not be ready"
      continue-on-error: true
    
    - name: Performance benchmark
      run: |
        # Run a quick performance check
        echo "Performance benchmark would run here in full CI environment"
        # npm run perf:benchmark
      continue-on-error: true
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/narravo_test

    - name: Upload performance artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-reports
        path: |
          lighthouse-results/
          docs/perf/benchmarks/
        retention-days: 30
        if-no-files-found: ignore